version: 2
jobs:
  build:
    working_directory: /go/src/github.com/dolab/objconv
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker: { reusable: true, docker_layer_caching: true }
      - run: GO111MODULE=on go mod tidy -v
      - run: GO111MODULE=on go vet ./...
      - run: GO111MODULE=on go test -v -race ./...
